jwt:
  header: Authorization
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes
spring:
  mvc:
    # 어떤 경로에 대한 요청의 응답으로 정적 파일을 응답으로 할지
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:/media/, classpath:/static
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    # username: sa
    # password: password
  jpa:
    hibernate:
      # 테이블 생성 시 create
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    # table create 후 data.sql 로 초기화할 때 사용
    # defer-datasource-initialization: true
  sql:
    init:
      mode: always