jwt:
  header: Authorization
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes

spring:
  mvc:
    # 어떤 경로에 대한 요청의 응답으로 정적 파일을 응답으로 할지
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:/media/, classpath:/static
  datasource:
    # driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: seonik
    password:
  jpa:
    hibernate:
      # 테이블 생성 시 create
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # table create 후 data.sql 로 초기화할 때 사용
    # defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379